name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      
    - name: Set up python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Install
      run: make install

    - name: Lint
      run: make lint

    - name: Test
      run: make test
